### ISSUE TITLE
Something weird

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/MyCourseware#2]
Have you ever worked with codeX RScript engine? [This game](https://vndb.org/v31427) is very weird, even if I used half-width katana, it still leaves spacing.
![image](https://github.com/Dir-A/VN_Localization_Tutorials/assets/81801486/e6f475af-f81d-40bc-99a0-046f12c551ae)
While the English characters doesn't
![image](https://github.com/Dir-A/VN_Localization_Tutorials/assets/81801486/35811529-b3f1-4b3e-b276-5ef4ec5d2ad6)

**Comment by Dir-A** [comment]
Never.
It's hard to say. 
Need to debug the game and see if the game itself controls the character distance or a system related API.
Maybe you could try replacing those characters via map other char.

**Comment by Cosetto** [comment]
Mapping huh, do you have any example? I have never seen this method before

**Comment by Dir-A** [comment]
We know a fact that the hexadecimal encoding of all characters are simply indexes of glyphs in a font file.
Generally, games displaying text will call the system's api to get the glyphs from the font file.
If the game has internal checks, such as checking for a character that needs to be spaced out
We can write a character in the game script that won't add spaces,
of course this character is certainly not the one we need to display.
But we can hook the system's api to replace this character with the one we need to display when it is called
This gets around some of the game's internal formatting of characters.

Of course there are many scenarios, here is just one of them.

**Comment by Cosetto** [comment]
Hmm, so since the new update of VnSubtitle is up, I was thinking of using the Subtitle tool to translate the game. What do you think?

**Comment by Dir-A** [comment]
VnSubtitle can do this, but it needs to adapt different game engine, which can be a lot of work.
Maybe you should rather consider something like a VNR, or some Textractor based software, it's easier.

**Comment by Cosetto** [comment]
Do you think it will work with this?
https://github.com/Dir-A/VN_Localization_Tutorials/assets/81801486/e6187aa9-fb3d-404f-8c61-3cd0ba4bbea6

**Comment by Dir-A** [comment]
Depends on the specific implementation.
Generally it's work if you're get the text via hook system API.
There are some that will search assembly code to get the text, may fail in this case.（with Themida Protected）

**Comment by Cosetto** [comment]
Yikes 0_0
Guess I have to give up on that part. Thanks anyway.
![Ded](https://github.com/Dir-A/VN_Localization_Tutorials/assets/81801486/95d505d6-68ae-4d6b-b770-521d8c863d3c)

**Comment by Cosetto** [comment]
By the way bro, where did you manage to find sublime text with shift-jis, gbk?

**Comment by Dir-A** [comment]
check this
https://github.com/seanliang/ConvertToUTF8
